import std.algorithm;
import std.conv;
import std.stdio;
import std.string;

void solve(long a, long b){
    writeln((0 == (a*b)%2) ? "Even" : "Odd");
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    auto input = stdin.byLine.map!split.joiner;

    long a;
    a = input.front.to!long;
    input.popFront;

    long b;
    b = input.front.to!long;
    input.popFront;

    solve(a, b);
    return 0;
}
