import std.algorithm;
import std.conv;
import std.stdio;
import std.string;

immutable string YES = "YES";
immutable string NO = "NO";

void solve(string S){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    auto input = stdin.byLine.map!split.joiner;

    string S;
    S = input.front.to!string;
    input.popFront;

    solve(S);
    return 0;
}
